#!/usr/bin/env bash

FEX_ROOT="${FEX_ROOT:-/home/critical/FEX}"
BUILD_DIR="${BUILD_DIR:-$FEX_ROOT/build-android-arm64-ninja}"
NDK_TOOLCHAIN="${NDK_TOOLCHAIN:-/home/critical/Android/Sdk/ndk/29.0.14206865/build/cmake/android.toolchain.cmake}"
BUILD_THUNKS="${BUILD_THUNKS:-OFF}"

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

cmake "$FEX_ROOT" \
  -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE="$NDK_TOOLCHAIN" \
  -DANDROID_ABI=arm64-v8a \
  -DANDROID_PLATFORM=android-30 \
  -DANDROID_STL=c++_shared \
  -DBUILD_FEXCONFIG=OFF \
  -DBUILD_FEX_LINUX_TESTS=OFF \
  -DBUILD_TESTING=OFF \
  -DBUILD_STEAM_SUPPORT=OFF \
  -DBUILD_THUNKS="$BUILD_THUNKS" \
  -DENABLE_GDB_SYMBOLS=OFF \
  -DENABLE_LTO=OFF \
  -DENABLE_CCACHE=OFF \
  -DENABLE_WERROR=OFF \
  -DENABLE_JEMALLOC=OFF \
  -DENABLE_JEMALLOC_GLIBC_ALLOC=OFF
